### ISSUE TITLE
[4.1.1] Error enabling the plugin

### ISSUE THREAD

**Issue by Norrox** [outobugi/Terrain3D#124]
I get this error, 
using Godot 4.1.1
Linux

Unable to load addon script from path: 'res://addons/terrain_3d/editor/editor.gd'. This might be due to a code error in that script.
Disabling the addon at 'res://addons/terrain_3d/editor/plugin.cfg' to prevent further errors.

**Comment by outobugi** [comment]
Need more info. Open editor.gd and see if there is any errors.

**Comment by TokisanGames** [comment]
What does your console say about editor.gd? There are more messages. You had no issues building? 

Other people are loading it fine on windows, Linux and osx.

**Comment by Norrox** [comment]
Sorry for my lack of information :) I'm using the one prebuilt by you for 4.1
here are some screenshots
![Screenshot_20230717_214249](https://github.com/outobugi/Terrain3D/assets/13393087/8486aa35-a651-46ec-8fe4-8ecdc20a349b)
![Screenshot_20230717_214316](https://github.com/outobugi/Terrain3D/assets/13393087/7bcc5ad0-c6a8-475e-b055-b986fe9ef82e)
![Screenshot_20230717_214329](https://github.com/outobugi/Terrain3D/assets/13393087/234cab8b-77cd-46bf-a997-e6b61e210128)

**Comment by TokisanGames** [comment]
I didn't provide a build for Linux, only windows. Note the win64 on the filename. You must build it yourself.

**Comment by Norrox** [comment]
> I didn't provide a build for Linux, only windows. Note the win64 on the filename. You must build it yourself.

Oh dang, sorry :D
