### ISSUE TITLE
Failing to build on MacOS Mojave.

### ISSUE THREAD

**Issue by drekay** [outobugi/Terrain3D#141]
**System:**
Mac OS Mojave 10.14.6 (18G103)
2.5 GHz Intel Core i7

I tried to use the release version - [terrain3d_0.8-alpha_gd4.1_osx_arm.zip] but got errors for mismatching architecture (mine is x86_64) so decided to build from source. I immediately ran into this scons error with or without specifying the platform:

```
$ scons platform=macos
scons: Reading SConscript files ...
Auto-detected 8 CPU cores available for build parallelism. Using 7 cores by default. You can override it with the -j argument.
Building for architecture universal on platform macos
scons: done reading SConscript files.
scons: Building targets ...
clang++ -o godot-cpp/src/godot.macos.template_debug.universal.o -c -std=c++17 -arch x86_64 -arch arm64 -O2 -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Igodot-cpp/src godot-cpp/src/godot.cpp
clang++ -o godot-cpp/src/classes/editor_plugin.macos.template_debug.universal.o -c -std=c++17 -arch x86_64 -arch arm64 -O2 -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Igodot-cpp/src godot-cpp/src/classes/editor_plugin.cpp
clang++ -o godot-cpp/src/classes/low_level.macos.template_debug.universal.o -c -std=c++17 -arch x86_64 -arch arm64 -O2 -DDEBUG_ENABLED -DDEBUG_METHODS_ENABLED -Igodot-cpp/gdextension -Igodot-cpp/include -Igodot-cpp/gen/include -Igodot-cpp/src godot-cpp/src/classes/low_level.cpp
....
....
....
In file included from godot-cpp/include/godot_cpp/variant/vector2.hpp:35:
godot-cpp/include/godot_cpp/core/math.hpp:569:9: error: call to 'abs' is
      ambiguous
        return std::abs(x);
               ^~~~~~~~
godot-cpp/include/godot_cpp/variant/vector2i.hpp:122:47: note: in instantiation
      of function template specialization 'godot::Math::abs<int>' requested here
        Vector2i abs() const { return Vector2i(Math::abs(x), Math::abs(y)); }
... and the rest of the stack trace ...
```

**Comment by drekay** [comment]
Sure thing. Thanks for clarifying.
Closing this issue to investigate godot-cpp setup for Terrain3D build.

**Comment by TokisanGames** [comment]
Also make sure you're on the appropriate version of godot-cpp. If you're building off of master that may be broken, while the version you actually want (eg. 4.1-stable) might build. Make sure you read the whole building from source page I linked.

**Comment by TokisanGames** [comment]
I'm experimenting with using Github's CI to build macos. The Github docker is an x64 system however observing the build command line I noticed it has keywords like `..._debug.universal.o ... -arch x86_64 -arch arm64`, which makes me think these binaries might work on both M1 and x64 architectures. Can I get some testers? Please download this and see if it works and let me know which architecture you have.

Download the artifact here:
https://github.com/TokisanGames/Terrain3D/actions/runs/6006513391
