### ISSUE TITLE
Godot Jolt Compatibility Issue: HeightmapCollider not a power of 2

### ISSUE THREAD

**Issue by QueenOfSquiggles** [outobugi/Terrain3D#154]
If unfamiliar, [Godot Jolt](https://github.com/godot-jolt/godot-jolt) is a GDExtension implementation of the Jolt Physics Engine. Boasts pretty great performance but does have a few drawbacks. Mainly HeightmapColliders are required to be a mesh that is a power of 2 size.

The specific error is here:
```BASH
E 0:00:11:0142   build: Failed to build height map shape with {height_count=1050625 width=1025 depth=1025}. Width/depth must be a power-of-two. This shape belongs to 'StaticBody3D:<StaticBody3D#75715577261>' and 0 other object(s).
  <C++ Error>    Condition "!is_power_of_2((uint32_t)width)" is true. Returning: {}
  <C++ Source>   src/shapes/jolt_height_map_shape_impl_3d.cpp:87 @ build()
```

I do believe it is very likely I can solve this through use of particular `clipmap_levels` and `clipmap_size` values. But reading through the wiki I wasn't able to find much documentation on what these values are and how they work. I have a surface-deep understanding of clipmap terrains, but I don't know what these values translate to, or how to force them to produce a power of two value. I'd definitely appreciate this being integrated into the addon, but a band-aid solution works for me now. I'm really loving this addon and saw Tokisan's video about it today. Excited to see what comes.

**Comment by TokisanGames** [comment]
Clipmap levels are for the mesh, not the collision shape.

Duplicate, see discussion. You're welcome to offer a solution there is you have one. 
https://github.com/outobugi/Terrain3D/discussions/152
