### ISSUE TITLE
Adding surface causes crash with no log

### ISSUE THREAD

**Issue by makaempffer** [outobugi/Terrain3D#156]
I just installed the latest version of the pluggin and Im working on a very new project so there is not much to it, the issue is when I try to add a surface and select any of the options(ImageTexture is what I tried most) godot just crashes. I tried getting a log or something but I couldn't. Running the program as Admin - Console didn't seem to fix the issue either.

**Comment by TokisanGames** [comment]
Crash already fixed in master. Duplicate https://github.com/outobugi/Terrain3D/issues/147. 
Read the wiki on setting up textures. Don't click new image texture, that does nothing.

**Comment by makaempffer** [comment]
Ok thx!
