### ISSUE TITLE
Renaming of Layer properties

### ISSUE THREAD

**Issue by tredokiller** [outobugi/Terrain3D#163]
In my opinion, something is wrong with the naming of layers "collision_layers" and "render_layers"

In the plugin, it looks like this:
![image](https://github.com/outobugi/Terrain3D/assets/81346829/0c13ab91-29a9-4814-b75d-623b9ea6e679)

But in other default nodes, it looks like this:
![image](https://github.com/outobugi/Terrain3D/assets/81346829/964804b9-09b1-4627-9029-1585085cf149)

Because of this, I can`t use checking by layer, because the name of the variable is different.
![image](https://github.com/outobugi/Terrain3D/assets/81346829/dcc191b8-c27e-49fc-8058-546e2f0af22c)

I think it would be better to rename it to "collision_layer" and "render_layer" like in other nodes

**Comment by TokisanGames** [comment]
It is Godot that is inconsistent.
* render_layers is `VisualInstance3D.layers`. All meshes have this.
* collision_layers is `CollisionObject3D.collision_layer`

There's also
* `CharacterBody3d.platform_wall_layers`
* `CharacterBody3d.platform_floor_layers`
* `NavigationServer/Agent*.avoidance_layers`
* `NavigationServer/Agent*.navigation_layers`
* `CanvasLayer.layer`

The questions I ask are:
* Should we be consistent with Godot's inconsistency and match render_layers with VI.layers, and collision_layer with CO.collision_layer?
* Should we be consistent to meaning and plurality, but inconsistent with Godot's physics, which I chose.
* Should be be inconsistent with meaning, but consistent with plurality, and inconsistent with Godot's render layers, which you suggest?

I'm considering.

For now you can query if it is a terrain
```
if collider is Terrain3D:
    ...
```

**Comment by TokisanGames** [comment]
I think we will match Godot's inconsistency. render_layers with VisualInstance.layers, and collision_layer with CollisionObject.collision_layer. If they fix their physics name to match everything else, we will change it back with them.
