### ISSUE TITLE
Terrain causes freezes and crashes when changing/opening a terrain scene

### ISSUE THREAD

**Issue by Saul2022** [outobugi/Terrain3D#172]
I am not sure if this is terrain  fault or the godot core though i didn’t experience this crash on zylan’s terrain and i have an igpu, though terrain works at good fps, the terrain is medium size and has 3 textures added with their diffuse and normal map..

**Comment by TokisanGames** [comment]
We can't help without information. There is nothing here for us to help you with. No hardware, no version, no information at all. 

Read the wiki troubleshooting article. Use the console. Read through the logs. Delete everything else in your scene and just run the terrain, or add your terrain storage to the demo scene to see if it's a problem with the terrain or the rest of your scene.

**Comment by Saul2022** [comment]
> We can't help without information. There is nothing here for us to help you with. No hardware, no version, no information at all.
> 
The graphics card has no name, just the driver is from amd radeon vega 3, it happen´s in both 4.1 and  4.2, and the weird stuff is that when making a new scene and using the same terrain storage it does not causse  freeze when changing to other scene, so might be godot fault. Closing as it seem´s godot core fault.
