### ISSUE TITLE
Collision does not work until debug_show_collision = true

### ISSUE THREAD

**Issue by DxUr** [outobugi/Terrain3D#180]
as the title you must set debug_show_collision to true to make the terrain have a collision shape but showing the collision wire frame make a bad performance (20~30 fps) and this not good for a smooth work flow

**Comment by Saul2022** [comment]
That because the terrain generates all the collision data for the whole terrain, it also causes freeze and crash when changing or entering a scene with it enabled. It works in game for you?

**Comment by TokisanGames** [comment]
Collision works in the game only, by design. The debug collision mode in the editor is for special, limited uses. If it's slow it's likely due to an underpowered system. Sorry. That's why we disable it in the editor. 

Does collision work for you in game when running the demo? If so that's how it's supposed to work.

**Comment by DxUr** [comment]
I'm using another plugin to place assets, and it requires the collision shape to detect where to place assets. Therefore, I won't be editing the terrain while enabling collision. However, the performance issues caused by the collision shape wireframes can be mitigated by adding an option to hide them.

**Comment by TokisanGames** [comment]
You can already hide them by turning off gizmos in your menu. We aren't draw them, so can't turn them on or off. We're only creating the collision shape. Godot and the settings you have set dictate what you see. 

The better solution for the asset tool is to integrate with [Terrain3D](https://github.com/outobugi/Terrain3D/wiki/Integrating-With-Terrain3D) . We already work on HungryProton's Scatter and I'm working with cookiebadger on his AssetPlacer, but you should encourage the author of your tool to support Terrain3D. Squeaky wheels get oiled.

**Comment by DxUr** [comment]
Thank you so mush
