### ISSUE TITLE
Terrain3D cannot build on Apple Silicon Mac

### ISSUE THREAD

**Issue by darthsteff** [outobugi/Terrain3D#187]
I
- checked out Terrain3D tag: **v0.8.1-alpha_gd4.1.1**
- checked out Godot-cpp tag: **godot-4.1.1-stable**
- built the Plugin using

**scons target=template_release platform=macos arch=arm64**

In Godot 4.1.1 I get the error 

Can't open dynamic library: /Users/steffenkluge/Development/Godot/OpenWorldTest/OpenWorldTest2/addons/terrain_3d/bin/libterrain.macos.debug.framework. Error: dlopen(/Users/steffenkluge/Development/Godot/OpenWorldTest/OpenWorldTest2/addons/terrain_3d/bin/libterrain.macos.debug.framework/libterrain.macos.debug, 0x0002): symbol not found in flat namespace '__ZN16Terrain3DStorage16SURFACE_MAX_SIZEE'.

I also built Godot 4.1.1 from source but that didn't change anything.

**Comment by TokisanGames** [comment]
First of all, can you build and run the godot-cpp test project?
https://github.com/outobugi/Terrain3D/wiki/Building-From-Source#how-can-i-make-sure-godot-cpp-is-the-right-version-and-working

If so, then it's a problem with Apple Clang. I don't know what their problem is. gcc and msvc work fine. If a solution can be found, I can change the code to accommodate. REGION_MAP_SIZE is the identical type and right next to it, yet it doesn't complain about that. 

What version is your OS?

What version is your compiler? `clang++ -v`

What version is your xcode sdk?

Does is help to change the line in terrain_3d_storage.h to:
`static const int32_t SURFACE_MAX_SIZE = 32;`
https://github.com/pytorch/pytorch/issues/84339
https://github.com/NVIDIA/MinkowskiEngine/pull/438

Try adding:
`env.Append(CXXFLAGS='-flat_namespace')` to SConstruct, after `env = SConscript`.
or
`env.Append(CXXFLAGS='-force_flat_namespace')`.


You can try adding `env.Append(LINKFLAGS='-Wl,-no_fixup_chains')` to SConstruct, after `env = SConscript`
Both haskell, perl and many other projects have had a similar issue with it. You can see a discussion about it here on my discord:
https://discord.com/channels/691957978680786944/1130291534802202735/1141028265750962337
https://gitlab.haskell.org/ghc/ghc/-/issues/22429
https://github.com/Perl/perl5/issues/20381

You can also change SURFACE_MAX_SIZE to a #define statement instead. Remove the line and add
`#define SURFACE_MAX_SIZE 32` outside of the class, above the `class Terrain3DStorage` line.

**Comment by darthsteff** [comment]
I was able to build and import the Godot-cpp test project successfully. I then built Terrain3D again and now it is working 🤷‍♂️

The only difference was that I ran scons without the arch and platform parameters like I had done before (I was trying to be smart which I clearly am not).

Thank you for your quick support!
Steff

**Comment by darthsteff** [comment]
To answer your questions:

I'm on macOS 13.4 (Ventura)
clang version is 14.0.3 (clang-1403.0.22.14.1) and
I run Xcode 14.3 however the command line tools are those of Xcode 15 Beta.

Kind regards,
Steff

**Comment by TokisanGames** [comment]
Thanks for the report. Hopefully this will help others with arm chips.

**Comment by TokisanGames** [comment]
I'm experimenting with using Github's CI to build macos. The Github docker is an x64 system however observing the build command line I noticed it has keywords like `..._debug.universal.o ... -arch x86_64 -arch arm64`, which makes me think these binaries might work on both M1 and x64 architectures. Can I get some testers? Please download this and see if it works and let me know which architecture you have.

Download the artifact here:
https://github.com/TokisanGames/Terrain3D/actions/runs/6006513391
